
- path: 
  - /add
  controller: Controllers\TransferController::add

- path: 
  - /download/(\d+)
  controller: Controllers\TransferController::download

- path: 
  - /file/(\d+)
  controller: Controllers\TransferController::grabFile
    
- path:
    - 
  controller: Controllers\TransferController::index

